name: Build and run buddy-benchmark

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: build opencv
      run: bash ./tests/Actions/BuildOpenCV.sh
    - name: build buddy-mlir
      run: bash ./tests/Actions/BuildBuddyMLIR.sh
    - name: build buddy-benchmark
      run: bash ./tests/Actions/BuildBuddyBenchmark.sh
